Vagrant.configure("2") do |config|
  
  config.vm.define "web" do |web|
    web.vm.box = "hashicorp/precise64"

    web.vbguest.auto_update = false
    web.vbguest.no_remote = true

    web.vm.provision "shell", inline: "sudo apt-get update -y; sudo apt-get install apache2 -y"
    
    web.vm.provision "file", source: "./static_website_src", destination: "/tmp/static_website_src_tmp"
    web.vm.provision "shell", inline: "mv /tmp/static_website_src_tmp/* /var/www"

    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.network "private_network", ip: "10.0.0.20"
  end

end
